[package]
name = "rustsweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
k_board = { version = "1.2.5", features = ["standar", "f", "alt_lower_letter", "ctrl_lower_letter", "lower_letter"] }
rand = "0.8.5"
